- name: Check whether each repository directory already exists
  ansible.builtin.stat:
    path: "{{ clone_git_folder }}/{{ item }}"
  loop:
    - ansible-kubernetes-helm-arc-runner
    - ansible-kubernetes-helm-istio
    - ansible-kubernetes-helm-argocd
    - ansible-kubernetes-cli-tools
    - ansible-kubernetes
    - ansible-containerd
    - ansible-cluster-configuration
    - ansible-containerd-nerdctl
    - ansible-nexus
    - ansible-kubernetes-helm-vault
    - ansible-kubernetes-helm-monitoring
    - ansible-sonarqube
    - ansible-jenkins
  register: clone_repository_status

- name: Checkout repositories that are not already present
  ansible.builtin.git:
    repo: "https://github.com/rhattox-ansible/{{ item.item }}.git"
    dest: "{{ item.stat.path }}"
    version: main
  loop: "{{ clone_repository_status.results }}"
  when: not item.stat.exists
  loop_control:
    label: "{{ item.item }}"