- name: Create github folder
  ansible.builtin.include_tasks: folder.yaml

- name: Clone all repos
  ansible.builtin.include_tasks: clone.yaml

- name: Fix repository permissions
  ansible.builtin.include_tasks: folder_permissions.yaml
